on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Cmake by docker action
    steps:
    - uses: actions/checkout@v1
    - name: cmake and make
      id: hello
      uses: seanzhengw/hello-world-docker-action@v2.0.1
